version: '2'
services:
    quikz-app:
        image: quikz
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://quikz-postgresql:5432/quikz
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://quikz-elasticsearch:9200
        ports:
            - 8080:8080
    quikz-postgresql:
        extends:
            file: postgresql.yml
            service: quikz-postgresql
    quikz-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: quikz-elasticsearch
