version: '2'
services:
    quikz-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/quikz/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=quikz
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
